# docker-compose.yml

version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - blockchain

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - ACCESS_TOKEN_SECRET=your_secret_key
      - SUPERADMIN_EMAIL=superadmin@example.com
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=system
      - DB_NAME=mydatabase
      - DB_PORT=3307
    depends_on:
      - db

  blockchain:
    build:
      context: ./blockchain
    ports:
      - "5173:5173"  # Update the port mapping
    environment:
      - INFURA_URL=https://sepolia.infura.io/v3/YOUR_INFURA_PROJECT_ID
      - CONTRACT_ADDRESS=0x49Ff66b40F77c78e65aafC07451e218b91EE0f03
      - YOUR_METAMASK_ADDRESS=YOUR_METAMASK_PUBLIC_ADDRESS
      - PRIVATE_KEY=YOUR_METAMASK_PRIVATE_KEY

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: system
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: system
    ports:
      - "3307:3306"
